### ISSUE TITLE
Suddently stops harvesting plants/barrels

### ISSUE THREAD

**Issue by Faplas** [Project-Sloth/ps-drugprocessing#118]
Me and 3 friends have tried this script and tested it for 2 days now, and i found some bugs that stops me from moving forward

- When i harvest it goes fine for the first like 20, but then i start to get to where it wont harvest anymore, no errors or anything, it just doesnt let me harvest, when i then reconnect and come back, i can again harvest, the only error i get is this qb-target
https://gyazo.com/3216156508b4ca2cecdcccba85d13e85 and its consistent with when i cant farm anymore

- It happends for all of us, and it starts when we harvest 20
- It doesnt solve it by leaving the area
- Clearing server and client cache doesnt help the problem

**Comment by zkiller30000** [comment]
> Me and 3 friends have tried this script and tested it for 2 days now, and i found some bugs that stops me from moving forward
> 
> * When i harvest it goes fine for the first like 20, but then i start to get to where it wont harvest anymore, no errors or anything, it just doesnt let me harvest, when i then reconnect and come back, i can again harvest, the only error i get is this qb-target
>   https://gyazo.com/3216156508b4ca2cecdcccba85d13e85 and its consistent with when i cant farm anymore
> * It happends for all of us, and it starts when we harvest 20
> * It doesnt solve it by leaving the area
> * Clearing server and client cache doesnt help the problem

I think that's not a problem, depending on which barrels you are collecting but every one of you have only 10 to collect. Unless another person comes and leaves couple of times, that person's barrels just stay there until a script restart and they can even be pushed down.

**Comment by Faplas** [comment]
but they are spawning, so everytime to collect one then a new one comes, so when you've picked 20 up, you end up having a field with 20 barrels you cant pickup.. if you wanted to limit the barrels, then dont set them to respawn i guess

about the barrels when a person leaves dont happen, because they spawn client sided as far as i know, so i dont see the same barrels as you do

**Comment by MrTrumpoi** [comment]
I can confirm this is an issue on our server too, I previously used the script in the past on another server and didn't have this issue. 

In trying to find out what's breaking and recreating it in a test environment as well as attempting a reinstall. I decided to delete the 'nearbyObject' check in the third-eye trigger as a test and it indicates an issue with assigning the 'nearbyObject, nearbyID' after a new prop is spawned. You will always be able to pick the first x props that spawn when you enter however after that it seems the spawning of new props after one is removed is bugging out for whatever reason and not assigning 'nearbyObject, nearbyID' correctly. It doesn't happen on every single pick up but eventually, it will cause all the props to have the issue of not being able to pick them up despite the third eye option being there.
![image](https://user-images.githubusercontent.com/7492720/229941921-79645f19-4004-4a58-a717-dc26648debda.png)

`RegisterNetEvent("ps-drugprocessing:pickHeroin", function()
	local playerPed = PlayerPedId()
	local coords = GetEntityCoords(playerPed)
	local nearbyObject, nearbyID

	for i=1, #PoppyPlants, 1 do
		if #(coords - GetEntityCoords(PoppyPlants[i])) < 2 then
			nearbyObject, nearbyID = PoppyPlants[i], i
		end
	end

	if IsPedOnFoot(playerPed) then
		isPickingUp = true
		TaskStartScenarioInPlace(playerPed, 'world_human_gardener_plant', 0, false)
		QBCore.Functions.Progressbar("search_register", Lang:t("progressbar.collecting"), 10000, false, true, {
			disableMovement = true,
			disableCarMovement = true,
			disableMouse = false,
			disableCombat = true,
		}, {}, {}, {}, function() -- Done
			ClearPedTasks(playerPed)
			SetEntityAsMissionEntity(nearbyObject, false, true)
			DeleteObject(nearbyObject)

			PoppyPlants[nearbyID] = nil -- Line 161
			spawnedPoppys -= 1

			TriggerServerEvent('ps-drugprocessing:pickedUpPoppy')
			isPickingUp = false

		end, function()
			ClearPedTasks(playerPed)
			isPickingUp = false
		end)
	end
end)`

**Comment by MrTrumpoi** [comment]
I decided to use version 1.0 and I no longer have this issue so will be using this version till a fix is pushed :)

**Comment by Faplas** [comment]
how can i get the older version then ?

**Comment by MrTrumpoi** [comment]
> how can i get the older version then ?

You just need to go to the releases section and download 1.0

**Comment by MonkeyWhisper** [comment]
Go ahead and fix it then.

**Comment by Faplas** [comment]
wait what?? what kind of answer is that, we are telling you there is an issue and trying to help you and this is the answer we get ?

**Comment by MonkeyWhisper** [comment]
> wait what?? what kind of answer is that, we are telling you there is an issue and trying to help you and this is the answer we get ?

Lol. How entitled you must feel.  This is an OPEN SOURCE PROJECT, do it yourself if you want to fix it.

**Comment by Faplas** [comment]
not at all entitled, but i was hoping for some sort of support, we are just trying to help

**Comment by imperial7eet** [comment]
I think this is probably related to setting the value of PoppyPlants[nearbyID] to nil instead of using table.remove to renumber the idx
