### ISSUE TITLE
Bypassing meth steps

### ISSUE THREAD

**Issue by tcantrell** [Project-Sloth/ps-drugprocessing#13]
You can actually bypass gathering the materials, and mixing by just going to the decrease heat target. It will give you a meth tray.

**Comment by MonkeyWhisper** [comment]
> 

Can you send in a video? 

Appreciate it.

**Comment by Yucifer777** [comment]
It happened with me too, you just need to go increase the temperature , you will get the chemicalvapor, then you decrease the temperature and you will get the tray without having any chemical on yourself or even doing the first step.

**Comment by tcantrell** [comment]
https://user-images.githubusercontent.com/63089185/165224852-a4b0b416-13a6-460d-871f-542cfc9bc82e.mp4

**Comment by Alivemonstor** [comment]
Fixed in new PR
