### ISSUE TITLE
LSD Processing

### ISSUE THREAD

**Issue by LoadedGuns** [Project-Sloth/ps-drugprocessing#133]
All the locations are thirdeyeable (left alt) to do the action, except processing LSD, when you walk into the polyzone it just has a E - Process LSD that follows you around while inside the zone, Ive dug through and tried rewritting the client and server scripts for LSD and messed into the target script and I can not find a solution, any ideas?

**Comment by LoadedGuns** [comment]
this was closed but was it changed? I thought I found the issue but it didnt seem to fix it when I tried changing the code up

**Comment by MonkeyWhisper** [comment]
Nothing was changed, nothing is broken. 

Revert your changes if you want. The script is open source, you can debug and fix it yourself. 

Thanks.

> this was closed but was it changed? I thought I found the issue but it didnt seem to fix it when I tried changing the code up
