### ISSUE TITLE
Coke Gather Issue

### ISSUE THREAD

**Issue by BTotonchi** [Project-Sloth/ps-drugprocessing#15]
i have the option to pick the coke leaf just when i actually click on it nothing happens and must be an issue with the event
![image](https://user-images.githubusercontent.com/96872295/165036275-f51a8b45-0f16-41bc-afc8-cd5866b5f081.png)

**Comment by MonkeyWhisper** [comment]
> i have the option to pick the coke leaf just when i actually click on it nothing happens and must be an issue with the event ![image](https://user-images.githubusercontent.com/96872295/165036275-f51a8b45-0f16-41bc-afc8-cd5866b5f081.png)

Thank you, this has been fixed with latest PR. 

Make sure to update.
