### ISSUE TITLE
Some targets missing

### ISSUE THREAD

**Issue by merpindia** [Project-Sloth/ps-drugprocessing#17]
Weed Processing- No target

HydrochloricAcid Farm- no target

Pickup Coke leafs- nothing happens

Heroin Processing - no target

**Comment by Alivemonstor** [comment]
this wasn't the case when i tested them all?
are you sure?

**Comment by Alivemonstor** [comment]
I'm looking over the readme and i added everything correctly so I'm not exactly sure what happened

**Comment by Alivemonstor** [comment]
yeah the things you're referencing weren't even in the readme

**Comment by MonkeyWhisper** [comment]
Already fixed in latest PR. Not sure what happened with the merges.

**Comment by merpindia** [comment]
i'll check and let you know
