### ISSUE TITLE
some things qb target isnt working with, get this error.

### ISSUE THREAD

**Issue by JoMichelle** [Project-Sloth/ps-drugprocessing#20]
![Snipaste_2022-04-25_10-54-04](https://user-images.githubusercontent.com/46945365/165146122-8f58d436-12b7-43d0-8553-45d8f0cead6a.png)

getting this error when trying to interact with some items, such as draco. weed, etc.

some "target items" dont work, ie you can have the leafs on you but it will not process.  the meth processing with all the acid takes my items, but gives nothing in return. i put all things in where they belong, maybe i'm missing something.

do i need to remove the original qb-drugs?

**Comment by MonkeyWhisper** [comment]
Check for new PR coming soon, it will fix this.
