### ISSUE TITLE
Weed Processing and Meth heating Mini-game

### ISSUE THREAD

**Issue by fuzeonspotify** [Project-Sloth/ps-drugprocessing#21]
Having an issue where the weed table doesn't allow me to process: https://discordapp.com/channels/897744257237000222/900180032935325707/968225836929015878

Also having an issue where my meth freezes after completing minigame: https://discordapp.com/channels/897744257237000222/900180032935325707/968018393611513867

No issues when pressing F8 or in my console. What could be causing these? I followed all the steps that I know of.

**Comment by Alivemonstor** [comment]
Processing weed is fixed :)

**Comment by fuzeonspotify** [comment]
> Processing weed is fixed :)

saw that thanks, sadly still having this meth issue :/
