### ISSUE TITLE
Bypass Weed Process

### ISSUE THREAD

**Issue by DarrianJCairns** [Project-Sloth/ps-drugprocessing#25]
Testing this out -  seems I can goto Weed Process and process without the Plants

**Comment by Alivemonstor** [comment]
probably just needs to check if you have the item again like the meth

**Comment by DarrianJCairns** [comment]
> probably just needs to check if you have the item again like the meth

Yeah maybe, also seen the issues with Bypassing the Meth lab stuff too, having that issue too

**Comment by Alivemonstor** [comment]
fixed with new pr
