### ISSUE TITLE
no interaction towards the herion plants

### ISSUE THREAD

**Issue by BTotonchi** [Project-Sloth/ps-drugprocessing#27]
![image](https://user-images.githubusercontent.com/96872295/165388871-ffa5eafc-b1c6-421f-b5c6-62c2e38b6e7e.png)

**Comment by Alivemonstor** [comment]
The plants currently have no collision so the target doesn't target it, might just revert these plants back to draw3dtext until collisions are fixed

**Comment by DarrianJCairns** [comment]
Yeah same

**Comment by MonkeyWhisper** [comment]
Fixed 

https://github.com/Project-Sloth/ps-drugprocessing/pull/35
