### ISSUE TITLE
MethLab

### ISSUE THREAD

**Issue by DarrianJCairns** [Project-Sloth/ps-drugprocessing#28]
After processing the items into Chem Mix - works fine
Then going to cool them to Chem Vapor - Works fine

But

When going to heat the Chem Vapor to Tray just gives another Vapor again doesnt work

Say it removes Chem mix to Vapor, doesnt issue a tray sadly

**Comment by Alivemonstor** [comment]
fixed in https://github.com/Project-Sloth/ps-drugprocessing/pull/29

**Comment by DarrianJCairns** [comment]
> fixed in #29

NICE!

**Comment by DarrianJCairns** [comment]
> 

Seems to still remove the Chemical Mix evern though I dont have have, and still give me the Vapor mix, I pushed your Commit btw

**Comment by DarrianJCairns** [comment]
> fixed in #29

NVM, server restart fixed it

**Comment by Alivemonstor** [comment]
sounds good!

**Comment by Alivemonstor** [comment]
So this is all fixed now?
