### ISSUE TITLE
Lab Fixes

### ISSUE THREAD

**Issue by DarrianJCairns** [Project-Sloth/ps-drugprocessing#30]
If I have the cocainekey third eyeing Draco to enter the lab doesn't work.

**Comment by DarrianJCairns** [comment]
https://gyazo.com/7fced6bf48605eaf72cd59271d68e827

Exit door doesnt work either

**Comment by Alivemonstor** [comment]
So if you pull the recent, there was a 3d draw text added, or if you 3rd eye on the lightswitch next to the door you can get out

**Comment by Alivemonstor** [comment]
getting in i will fix now

**Comment by DarrianJCairns** [comment]
> getting in i will fix now

np bud :)

**Comment by Alivemonstor** [comment]
https://gyazo.com/e8edd64ec57eab2c1c5e7d7317f08405

does this show up for you?

**Comment by DarrianJCairns** [comment]
> 

Yeah got it now lmao... Dunno if it should be the door... nobody would think of that haha!!!

**Comment by Alivemonstor** [comment]
> > 
> 
> Yeah got it now lmao... Dunno if it should be the door... nobody would think of that haha!!!

yeah I'm changing it to the door

**Comment by Alivemonstor** [comment]
okay

**Comment by Alivemonstor** [comment]
done

**Comment by DarrianJCairns** [comment]
> done

Let me check it out, where do you go to Process the Brick? Im at "vector3(1092.9, -3196.65, -38.99)" cant see anything

**Comment by Alivemonstor** [comment]
fixed enter aswell

**Comment by Alivemonstor** [comment]
> 1092.9, -3196.65, -38.99

the table

**Comment by DarrianJCairns** [comment]
> 

Is that to cut the "coke_small_brick" ?
