### ISSUE TITLE
Infinite cokain pile production

### ISSUE THREAD

**Issue by Flobbah** [Project-Sloth/ps-drugprocessing#39]
It's possible to infinitly process cocaleafs to cocain piles.

**Comment by Alivemonstor** [comment]
do you mind posting a video?

**Comment by Flobbah** [comment]
https://streamable.com/ut0tmn

**Comment by Flobbah** [comment]
The local "hasitem1" and "hasitem2" are missing.
Maybe thats what's wrong

**Comment by Flobbah** [comment]
Found something else. "hasitem1" is never set to false after setting it to true. So yeah, its possible to infinit make coke atm.
Here you can see how I (maybe) fixed it: https://streamable.com/180heb
I'm too stupid to do PR's so maybe someone could do it?

**Comment by MonkeyWhisper** [comment]
Alright, pretty sure it was almost impossible since as you Alive did, I hade an item check. I deployed your PR already. Thank you sir!
