### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by JReagan618** [Project-Sloth/ps-drugprocessing#41]
-When adding the chemicals in the first part of the Meth Processing, the process is done, the progress bar is gone, stand there and nothing else happens, so you go to the next step and qb-notify says "processing has stopped because you abandoned the area". The was nothing more to do for that step?
-When processing the chemicals at Humane, tho you're selecting to make and are recieving LSA, the notify is showing "The Sulfuric Acid Process Was Successful".
- thionyl_chloride processing doesn't seem to do anything. I gave myself thionyl_chloride and nothing happens at the processing spot.
-No where to process poppy seeds/heroin.

**Comment by Alivemonstor** [comment]
https://github.com/Project-Sloth/ps-drugprocessing/pull/45
