### ISSUE TITLE
No Meth given when packing.

### ISSUE THREAD

**Issue by S0lan** [Project-Sloth/ps-drugprocessing#49]
When "packing" the meth, the process bar shows up, but when it is done no item is given, and the meth tray is not removed. 
Latest update #47

**Comment by MonkeyWhisper** [comment]
Did this started happen recently or was this always happening?

**Comment by MonkeyWhisper** [comment]
Sorry, I did not meant to close this issue.

**Comment by Alivemonstor** [comment]
i dont see the issue in the code where this occurs, ill try this in an hour when i get home

**Comment by MonkeyWhisper** [comment]
Fixed
