### ISSUE TITLE
Cannot harvest plants

### ISSUE THREAD

**Issue by jayskee** [Project-Sloth/ps-drugprocessing#55]
Most plants do not work when harvesting - I've already made the #53 merge and it still did not fix my issue.

Please refer to the video: https://medal.tv/games/gta-v/clips/lu13kTETG-Rss/d133727xHbxN?invite=cr-MSw2aVMsNjgzMzQ2NTks

**Comment by Alivemonstor** [comment]
Ill take a look at the code when i get home.most likely another wrong config option or something stupid

**Comment by jayskee** [comment]
Thanks very much <3

**Comment by jayskee** [comment]
Any update on this? ^_^

**Comment by MonkeyWhisper** [comment]
I tested and it works fine

**Comment by yanpla** [comment]
This happens to me too when there are multiple players in a drug spawn zone. When one player cant harvest a plant the other can.
