### ISSUE TITLE
Coke Lab Refine Not Working

### ISSUE THREAD

**Issue by Nadunnissanka** [Project-Sloth/ps-drugprocessing#56]
I have had 10 Coke Powder and 5 Baking Soda. But still when I try to refine it does not give feedback or output. Using third eye action to refine does nothing. No errors on console.

**Comment by troubleNZ** [comment]
i had the same problem until i looked closer and saw that `finescale` is also a required item and is checked for after you have both ingredients.

**Comment by Nadunnissanka** [comment]
Thank You!
