### ISSUE TITLE
Cannot process small coke bricks

### ISSUE THREAD

**Issue by SagginChair** [Project-Sloth/ps-drugprocessing#60]
Client/Coke/ Line 106			

end, 'coke_small_brick', Config.CokeProcessing.SmallCokeBrick)
This line needs to be changed to
			end, 'coke_small_brick', Config.CokeProcessing.SmallBrick)

It's pulling the wrong config for hasitem check.

**Comment by MonkeyWhisper** [comment]
> 

Make a PR for this

**Comment by MonkeyWhisper** [comment]
You are right, there's a wrong config 

https://github.com/Project-Sloth/ps-drugprocessing/commit/292cffb8e6b9ee5aae698af7ab27dd3fc94867f6

Fixed, thanks
