### ISSUE TITLE
Can't process coca leaves 

### ISSUE THREAD

**Issue by ashleyjrobinson** [Project-Sloth/ps-drugprocessing#61]
Few reporting this in the Discord and I have the same issue with a fresh install

**Comment by WillIShocker** [comment]
I have this same issue.
![Screenshot_43](https://user-images.githubusercontent.com/87030078/172010877-931d0653-5a44-41d4-9378-484305e840a8.png)

**Comment by WillIShocker** [comment]
Just figured this out. Need item - trimming_scissors to process coke leaves. This is not in the image list but is in the inventory items to add. Until they fix the image, you can always set it to zero. Like this.
![Screenshot_44](https://user-images.githubusercontent.com/87030078/172011920-77ab0c17-b88f-4f1f-90aa-b59af08752e4.png)
.

**Comment by MonkeyWhisper** [comment]
Fixed on this PR

https://github.com/Project-Sloth/ps-drugprocessing/pull/62
