### ISSUE TITLE
Cannot process thionylchloride

### ISSUE THREAD

**Issue by WillIShocker** [Project-Sloth/ps-drugprocessing#63]
I get this attached error while attempting to process thionylchloride. Cannot process thi clo
![Screenshot_45](https://user-images.githubusercontent.com/87030078/172020607-a74867a4-ba84-41dd-8650-55dcaa8d9d2a.png)

**Comment by WillIShocker** [comment]
Also dont believe there is an area to get the required item

**Comment by WillIShocker** [comment]
To add to this. I have plenty of the items required. I only receive the error when I try to process.

**Comment by zWyzzzzz** [comment]
@WillIShocker this should be fix the probleme https://github.com/Project-Sloth/ps-drugprocessing/pull/64
