### ISSUE TITLE
coca powder processing item checks

### ISSUE THREAD

**Issue by RoyalLasky** [Project-Sloth/ps-drugprocessing#65]
There may be an issue with coke processing with the processing coca powder part, in client/coke.lua
```
QBCore.Functions.TriggerCallback('ps-drugprocessing:validate_items', function(result)
                if result then
                    CutCokePowder()
                else
                    QBCore.Functions.Notify(Lang:t("error.not_all_items"), 'error')
                end
            end, check)
```
If you don't have the right items, no matter if its the 1 finescale, 5 baking soda or 10 cocaine it just throws the same error "You do not have the right items needed". You need the correct amount(or more) of all items for the check to pass then it works fine. Other steps it tells you specifically what item you are missing.

There is a check serverside (server/coke.lua) for baking soda & cocaine, but it does not get triggered because the client side forces you to have the right amount. There is no actual check and error for missing the finescale at all.
```if Player.Functions.RemoveItem('coke', Config.CokeProcessing.Coke) then
        if Player.Functions.RemoveItem('bakingsoda', Config.CokeProcessing.BakingSoda) then
TriggerClientEvent('QBCore:Notify', src, Lang:t("error.no_bakingsoda_amount"), "error")
        end
    else
        TriggerClientEvent('QBCore:Notify', src, Lang:t("error.no_cokain_amount"), "error")```

**Comment by MonkeyWhisper** [comment]
That's not a mistake. You need to have all the items in order to craft it.
