### ISSUE TITLE
Respawn issue/radius issue

### ISSUE THREAD

**Issue by RoyalLasky** [Project-Sloth/ps-drugprocessing#66]
There seems to be an issue with respawning. None of the items to be picked respawn unless you leave the area and come back. Sodium Hydroxide & heroin field are the exceptions(See below). Also, it seems like none of these are following the radius I set. No matter what I set(I set it to 20 for e.x), they seem to keep spawning at an 100 radius.

Note: I've only changed the animations for picking chemicals, and the progressbar for it.. that is it.

Weedfield - Does not respawn unless you leave the area and come back
HydrochloricAcidFar - Does not respawn unless you leave the area and come back
SulfuricAcidFarm - Does not respawn unless you leave the area and come back
SodiumHydroxideFarm -Respawns almost instantly, always in the same spots.
chemicalsfield - Does not respawn unless you leave the area and come back
cokefield - Does not respawn unless you leave the area and come back
heroinfield - Looks to be respawning perfectly fine, not following radius set
	
	Edit: Heres a video: https://youtu.be/iPGEQxkg0EM

**Comment by MonkeyWhisper** [comment]
I'll take a look at it.

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-drugprocessing/issues/68

Tie together

**Comment by InfamousRL** [comment]
> #68
> 
> Tie together

Not the same but okay all good will just wait for an update thanks

**Comment by HBOllie** [comment]
So the issue with the radius's is that in the client.lua for any of the farms they are all set to 50.0 so the config doesn't change it

**Comment by ElvisMatias** [comment]
just reduce the respawn zone to 10.0, i had the same problem you mentioned, i just reduced the distance from 50.0 to 10.0 and it's fixed, items respawn instantly when picked up

CreateThread(function()
	local weedZone = CircleZone:Create(Config.CircleZones.WeedField.coords, 10.0, {
		name = "ps-weedzone",
		debugPoly = false
	})
	weedZone:onPlayerInOut(function(isPointInside, point, zone)
        if isPointInside then
            inWeedField = true
            SpawnWeedPlants()
        else
            inWeedField = false
        end
    end)
end)

**Comment by MonkeyWhisper** [comment]
> So the issue with the radius's is that in the client.lua for any of the farms they are all set to 50.0 so the config doesn't change it
> 
> ![image](https://user-images.githubusercontent.com/10517362/173416317-25f828a2-2842-4c5c-9e27-b0e6de26ce16.png)

Can you make a PR? I'll take a look at it :)

**Comment by MonkeyWhisper** [comment]
Ops, sorry.. closed by accident.

**Comment by MonkeyWhisper** [comment]
This was fixed here https://github.com/Project-Sloth/ps-drugprocessing/pull/79
