### ISSUE TITLE
Few issues and possible features

### ISSUE THREAD

**Issue by InfamousRL** [Project-Sloth/ps-drugprocessing#68]
So i have poly zones setup and working great but only for a few things.

Weed: 10 or so spawns per player
Coke Leaves: 10 or so spawns per player
Poppies: 10 or so spawns per player
Chemicals: 10 or so spawns per player
Sodium: 1 spawn per player
Hydro: 1 spawn per player
Sulfuric: 1 spawn per player

No idea why the Sodium, hydro and sulfuric only spawn one per player,

One thing id love too see if just too be able too set a spawn limit within the poly zone/circle zones, and remove the playerpedid stuff cause then servers run into the issue on if 5 people turn up too weed then that 10 plants turns into 50+ and you have too try and find the plants that belong too your ID instead of being able too just pick any plant, instead maybe could have a this plate is being picked if someone try's too pick the same plant? 

Otherwise i love this script and would love too see it evolve into the must have drug script for any fivem server.

**Comment by MonkeyWhisper** [comment]
Already an issue

**Comment by MonkeyWhisper** [comment]
> So i have poly zones setup and working great but only for a few things.
> 
> Weed: 10 or so spawns per player Coke Leaves: 10 or so spawns per player Poppies: 10 or so spawns per player Chemicals: 10 or so spawns per player Sodium: 1 spawn per player Hydro: 1 spawn per player Sulfuric: 1 spawn per player
> 
> No idea why the Sodium, hydro and sulfuric only spawn one per player,
> 
> One thing id love too see if just too be able too set a spawn limit within the poly zone/circle zones, and remove the playerpedid stuff cause then servers run into the issue on if 5 people turn up too weed then that 10 plants turns into 50+ and you have too try and find the plants that belong too your ID instead of being able too just pick any plant, instead maybe could have a this plate is being picked if someone try's too pick the same plant?
> 
> Otherwise i love this script and would love too see it evolve into the must have drug script for any fivem server.

Send me a DM in Discord, I want to pick your brain on new features. MonkeyWhisper#0001
