### ISSUE TITLE
weed lab issue

### ISSUE THREAD

**Issue by InitialD09** [Project-Sloth/ps-drugprocessing#76]
hi how do i get weed lab to get working i dont understand to weed and coke lab have the same coords

**Comment by amgmacht** [comment]
by setting your own weed lab, just reset the cordniates then it's not the same as with cocaine.

**Comment by InitialD09** [comment]
> by setting your own weed lab, just reset the cordniates then it's not the same as with cocaine.

oh okay i'll try i thought that you could change it in config file now i figured it out
thanks. man
