### ISSUE TITLE
Target Walter and Draco

### ISSUE THREAD

**Issue by Numba9ine** [Project-Sloth/ps-drugprocessing#89]
What do you need to interact with both targets? I attempted many things but can't seem to figure it out.

**Comment by WalterWyoming** [comment]
You need a methkey (item).  It's right there in the code.  Literally search for Walter or Draco in the code and then you'll see what items they call for.

**Comment by WalterWyoming** [comment]
> What do you need to interact with both targets? I attempted many things but can't seem to figure it out.

You need a "methkey" item and it will let you into the door there and bring you to the lab where you can third eye the bin below and make meth (if you have the items for that too).

All you do is open the code and search for Walter or Draco and it will bring you to the code where you can see what each one does and what items they require.

**Comment by MashOff** [comment]
> > What do you need to interact with both targets? I attempted many things but can't seem to figure it out.
> 
> You need a "methkey" item and it will let you into the door there and bring you to the lab where you can third eye the bin below and make meth (if you have the items for that too).
> 
> All you do is open the code and search for Walter or Draco and it will bring you to the code where you can see what each one does and what items they require.

I only can use admin panel to get "methkey" how to get it as regular member in city? Do I need other script?
