### ISSUE TITLE
Coke Processing Config math.random is not actually randomizing

### ISSUE THREAD

**Issue by Shady8091** [Project-Sloth/ps-drugprocessing#91]
I've noticed over the past few days for everyone that has been doing it, that the coke processing has been pushing the same exact amount each time until either server or script restarts. Looking into it, from what I can gather is that the config isn't refreshing the random number each time the event is triggered. It sets one number each restart and sends it each time to the event. 

I don't really know how to do a pull request here to be honest, but I was able to resolve this and get varying numbers each event trigger by moving the math.random to the server event on the coke processing and the small bricks. Attached image is how I fixed it. Lines 18 and 36 added and changed the Config.CokeProcessing.ProcessCokeLeaf(lines 21 and 23) and Config.CokeProcessing.SmallCokeBrick(lines 40 and 43) to the local total.

![image](https://user-images.githubusercontent.com/91345180/187841823-4b9140b1-0b51-4366-9d69-ffc20305d32f.png)

if this isnt right, let me know, but it is working fine for me.

I also assume that the math.random for meth processing is also causing issues, but I have not looked into that as of this moment.

**Comment by Smokezz6969** [comment]
![image](https://user-images.githubusercontent.com/99103156/188284209-10a51ae4-e7b4-4bad-b92c-cc6e80557377.png)
For me the qb eye is not working on coke plants do you know why?

**Comment by Smokezz6969** [comment]
@Shady8091

**Comment by Shady8091** [comment]
> @Shady8091

If its a newer version of qb-target, i know theres issues with targeting entities. That could be it. or vice versa. older qb-target and newer ps-drugprocessing maybe causes that

**Comment by AndreasFromDanmark** [comment]
I have the same issue with the Target, so i cant harvest the drug in the server

**Comment by MonkeyWhisper** [comment]
Fixed on https://github.com/Project-Sloth/ps-drugprocessing/pull/98
![image](https://user-images.githubusercontent.com/82112471/190304310-04f7842f-71ed-4083-9231-608beb2c01ab.png)
